-- Bu dosya isteğe bağlı başlangıç verilerini (seeding) barındırmak için kullanılabilir.
-- Örnek:
-- INSERT INTO experiences (company_name, title, start_date, is_current, description)
-- VALUES ('ResuMesh', 'Open Source Contributor', '2023-01-01', true, 'Building intelligent portfolio systems.');

INSERT INTO "public"."app_settings" ("key", "value") VALUES
('sections', '{"projects": true, "certificates": true, "videos": true, "experiences": true}'::jsonb),
('socials', '[{"id": "github", "platform": "github", "url": "https://github.com/AtaCanYmc", "label": "GitHub"}, {"id": "linkedin", "platform": "linkedin", "url": "https://www.linkedin.com/in/ata-can-yaymac\\u0131/", "label": "LinkedIn"}, {"id": "devto", "platform": "devto", "url": "https://dev.to/atacanymc", "label": "Dev.to"}, {"id": "medium", "platform": "medium", "url": "https://medium.com/@atacanymc", "label": "Medium"}]'::jsonb),
('footer', '{"email": "atacanymc@gmail.com"}'::jsonb),
('marquee', '["React.js", "Vite.js", "Java", "SpringBoot", "TypeScript", "JavaScript", "Tailwind CSS", "Python", "FastAPI", "PostgreSQL", "PL/SQL", "C#", ".NET", "Supabase", "Firebase", "MongoDB", "Docker", "Node.js", "Next.js", "GraphQL"]'::jsonb),
('en', '{"hero": {"name": "Ata Can", "fullName": "Ata Can Yaymac\\u0131", "avatarSubtitle": "Crafting digital experiences", "avatarImage": "/images/profile_pic.jpeg", "title": "I bridge the gap between AI Workflows and Financial Technologies.", "description": "With a Computer Engineering background from Dokuz Eylul University, I specialize in scalable backend architectures and automation processes. I transform complex data into meaningful insights using modern web technologies.", "resumeLink": "/resumes/resume.pdf"}, "metrics": [{"id": 1, "icon": "code", "value": "25+", "label": "Active Projects", "color": "blue"}, {"id": 2, "icon": "book", "value": "40+", "label": "Technical Articles", "color": "indigo"}, {"id": 3, "icon": "star", "value": "4+", "label": "Years Experience", "color": "purple"}]}'::jsonb),
('tr', '{"hero": {"name": "Ata Can", "fullName": "Ata Can Yaymac\\u0131", "avatarSubtitle": "Dijital deneyimler tasarlay\\u0131yorum", "avatarImage": "/images/profile_pic.jpeg", "title": "Yapay Zeka \\u0130\\u015f Ak\\u0131\\u015flar\\u0131 ve Finansal Teknolojiler aras\\u0131nda köprü kuruyorum.", "description": "Dokuz Eylül Üniversitesi Bilgisayar Mühendisliği geçmişimle, ölçeklenebilir backend mimarileri ve otomasyon süreçleri üzerine çalışıyorum. Modern web teknolojileriyle karmaşık verileri anlamlı içgörülere dönüştürüyorum.", "resumeLink": "/resumes/resume.pdf"}, "metrics": [{"id": 1, "icon": "code", "value": "25+", "label": "Aktif Proje", "color": "blue"}, {"id": 2, "icon": "book", "value": "40+", "label": "Teknik Makale", "color": "indigo"}, {"id": 3, "icon": "star", "value": "4+", "label": "Yıl Deneyim", "color": "purple"}]}'::jsonb)
ON CONFLICT ("key") DO UPDATE SET "value" = EXCLUDED."value";
